version: '2.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "p45sw0rd"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "school"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  teacherer:
    image: adminer
    restart: always
    ports:
      - 8080:8080