version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.19
    steps:
      - checkout
      - run:
          name: Build and test
          command: go mod download && go test ./...
#      - run:
#          name: Create docker image and publish
#          command: docker build -t school-system-api . && docker tag my-repository my-repository:my-tag && docker push my-repository:my-tag